### ISSUE TITLE
lower flops input

### ISSUE THREAD

**Issue by jc-louis** [calum-bird/howmanyparams.com#2]
If I understood correctly, the minimum flops is 1e21 which is quite large.
According to https://arxiv.org/abs/2212.14034, one rtxa4000 for one day is 5e18 flops.

**Comment by calum-bird** [comment]
Yes that is correct. The reasoning behind 1e21 FLOPs as a baseline is that the LLMs these scaling laws were modelled on are typically >1B parameters, and thus require orders of magnitude more than 1e18 FLOPs. I plan on adding a section to visualize the amount of compute required in terms of GPU count over time, which should help make this more clear.

That being said, it would be interesting to investigate smaller models, and I will consider lowering the threshold once I've gotten around to a few more features and bug fixes. Will keep this issue open with that in mind!

**Comment by calum-bird** [comment]
Closing as latest [update](https://github.com/calum-bird/howmanyparams.com/commit/c77e9315034635e737022546beab118b250c911a) lets you specify the exponent.
